# CMake generated Testfile for 
# Source directory: T:/Kyle_Shepherd/games/Beyond-All-Reason/data/games/spring/test
# Build directory: T:/Kyle_Shepherd/games/Beyond-All-Reason/data/engine/dev_engine/test
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(testUDPListener "T:/Kyle_Shepherd/games/Beyond-All-Reason/data/engine/dev_engine/test/Debug/test_UDPListener.exe")
  set_tests_properties(testUDPListener PROPERTIES  _BACKTRACE_TRIPLES "T:/Kyle_Shepherd/games/Beyond-All-Reason/data/games/spring/test/CMakeLists.txt;63;add_test;T:/Kyle_Shepherd/games/Beyond-All-Reason/data/games/spring/test/CMakeLists.txt;104;add_spring_test;T:/Kyle_Shepherd/games/Beyond-All-Reason/data/games/spring/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(testUDPListener "T:/Kyle_Shepherd/games/Beyond-All-Reason/data/engine/dev_engine/test/Release/test_UDPListener.exe")
  set_tests_properties(testUDPListener PROPERTIES  _BACKTRACE_TRIPLES "T:/Kyle_Shepherd/games/Beyond-All-Reason/data/games/spring/test/CMakeLists.txt;63;add_test;T:/Kyle_Shepherd/games/Beyond-All-Reason/data/games/spring/test/CMakeLists.txt;104;add_spring_test;T:/Kyle_Shepherd/games/Beyond-All-Reason/data/games/spring/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(testUDPListener "T:/Kyle_Shepherd/games/Beyond-All-Reason/data/engine/dev_engine/test/MinSizeRel/test_UDPListener.exe")
  set_tests_properties(testUDPListener PROPERTIES  _BACKTRACE_TRIPLES "T:/Kyle_Shepherd/games/Beyond-All-Reason/data/games/spring/test/CMakeLists.txt;63;add_test;T:/Kyle_Shepherd/games/Beyond-All-Reason/data/games/spring/test/CMakeLists.txt;104;add_spring_test;T:/Kyle_Shepherd/games/Beyond-All-Reason/data/games/spring/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(testUDPListener "T:/Kyle_Shepherd/games/Beyond-All-Reason/data/engine/dev_engine/test/RelWithDebInfo/test_UDPListener.exe")
  set_tests_properties(testUDPListener PROPERTIES  _BACKTRACE_TRIPLES "T:/Kyle_Shepherd/games/Beyond-All-Reason/data/games/spring/test/CMakeLists.txt;63;add_test;T:/Kyle_Shepherd/games/Beyond-All-Reason/data/games/spring/test/CMakeLists.txt;104;add_spring_test;T:/Kyle_Shepherd/games/Beyond-All-Reason/data/games/spring/test/CMakeLists.txt;0;")
else()
  add_test(testUDPListener NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(testILog "T:/Kyle_Shepherd/games/Beyond-All-Reason/data/engine/dev_engine/test/Debug/test_ILog.exe")
  set_tests_properties(testILog PROPERTIES  _BACKTRACE_TRIPLES "T:/Kyle_Shepherd/games/Beyond-All-Reason/data/games/spring/test/CMakeLists.txt;63;add_test;T:/Kyle_Shepherd/games/Beyond-All-Reason/data/games/spring/test/CMakeLists.txt;122;add_spring_test;T:/Kyle_Shepherd/games/Beyond-All-Reason/data/games/spring/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(testILog "T:/Kyle_Shepherd/games/Beyond-All-Reason/data/engine/dev_engine/test/Release/test_ILog.exe")
  set_tests_properties(testILog PROPERTIES  _BACKTRACE_TRIPLES "T:/Kyle_Shepherd/games/Beyond-All-Reason/data/games/spring/test/CMakeLists.txt;63;add_test;T:/Kyle_Shepherd/games/Beyond-All-Reason/data/games/spring/test/CMakeLists.txt;122;add_spring_test;T:/Kyle_Shepherd/games/Beyond-All-Reason/data/games/spring/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(testILog "T:/Kyle_Shepherd/games/Beyond-All-Reason/data/engine/dev_engine/test/MinSizeRel/test_ILog.exe")
  set_tests_properties(testILog PROPERTIES  _BACKTRACE_TRIPLES "T:/Kyle_Shepherd/games/Beyond-All-Reason/data/games/spring/test/CMakeLists.txt;63;add_test;T:/Kyle_Shepherd/games/Beyond-All-Reason/data/games/spring/test/CMakeLists.txt;122;add_spring_test;T:/Kyle_Shepherd/games/Beyond-All-Reason/data/games/spring/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(testILog "T:/Kyle_Shepherd/games/Beyond-All-Reason/data/engine/dev_engine/test/RelWithDebInfo/test_ILog.exe")
  set_tests_properties(testILog PROPERTIES  _BACKTRACE_TRIPLES "T:/Kyle_Shepherd/games/Beyond-All-Reason/data/games/spring/test/CMakeLists.txt;63;add_test;T:/Kyle_Shepherd/games/Beyond-All-Reason/data/games/spring/test/CMakeLists.txt;122;add_spring_test;T:/Kyle_Shepherd/games/Beyond-All-Reason/data/games/spring/test/CMakeLists.txt;0;")
else()
  add_test(testILog NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(testSyncedPrimitive "T:/Kyle_Shepherd/games/Beyond-All-Reason/data/engine/dev_engine/test/Debug/test_SyncedPrimitive.exe")
  set_tests_properties(testSyncedPrimitive PROPERTIES  _BACKTRACE_TRIPLES "T:/Kyle_Shepherd/games/Beyond-All-Reason/data/games/spring/test/CMakeLists.txt;63;add_test;T:/Kyle_Shepherd/games/Beyond-All-Reason/data/games/spring/test/CMakeLists.txt;136;add_spring_test;T:/Kyle_Shepherd/games/Beyond-All-Reason/data/games/spring/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(testSyncedPrimitive "T:/Kyle_Shepherd/games/Beyond-All-Reason/data/engine/dev_engine/test/Release/test_SyncedPrimitive.exe")
  set_tests_properties(testSyncedPrimitive PROPERTIES  _BACKTRACE_TRIPLES "T:/Kyle_Shepherd/games/Beyond-All-Reason/data/games/spring/test/CMakeLists.txt;63;add_test;T:/Kyle_Shepherd/games/Beyond-All-Reason/data/games/spring/test/CMakeLists.txt;136;add_spring_test;T:/Kyle_Shepherd/games/Beyond-All-Reason/data/games/spring/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(testSyncedPrimitive "T:/Kyle_Shepherd/games/Beyond-All-Reason/data/engine/dev_engine/test/MinSizeRel/test_SyncedPrimitive.exe")
  set_tests_properties(testSyncedPrimitive PROPERTIES  _BACKTRACE_TRIPLES "T:/Kyle_Shepherd/games/Beyond-All-Reason/data/games/spring/test/CMakeLists.txt;63;add_test;T:/Kyle_Shepherd/games/Beyond-All-Reason/data/games/spring/test/CMakeLists.txt;136;add_spring_test;T:/Kyle_Shepherd/games/Beyond-All-Reason/data/games/spring/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(testSyncedPrimitive "T:/Kyle_Shepherd/games/Beyond-All-Reason/data/engine/dev_engine/test/RelWithDebInfo/test_SyncedPrimitive.exe")
  set_tests_properties(testSyncedPrimitive PROPERTIES  _BACKTRACE_TRIPLES "T:/Kyle_Shepherd/games/Beyond-All-Reason/data/games/spring/test/CMakeLists.txt;63;add_test;T:/Kyle_Shepherd/games/Beyond-All-Reason/data/games/spring/test/CMakeLists.txt;136;add_spring_test;T:/Kyle_Shepherd/games/Beyond-All-Reason/data/games/spring/test/CMakeLists.txt;0;")
else()
  add_test(testSyncedPrimitive NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(testRectangleOverlapHandler "T:/Kyle_Shepherd/games/Beyond-All-Reason/data/engine/dev_engine/test/Debug/test_RectangleOverlapHandler.exe")
  set_tests_properties(testRectangleOverlapHandler PROPERTIES  _BACKTRACE_TRIPLES "T:/Kyle_Shepherd/games/Beyond-All-Reason/data/games/spring/test/CMakeLists.txt;63;add_test;T:/Kyle_Shepherd/games/Beyond-All-Reason/data/games/spring/test/CMakeLists.txt;151;add_spring_test;T:/Kyle_Shepherd/games/Beyond-All-Reason/data/games/spring/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(testRectangleOverlapHandler "T:/Kyle_Shepherd/games/Beyond-All-Reason/data/engine/dev_engine/test/Release/test_RectangleOverlapHandler.exe")
  set_tests_properties(testRectangleOverlapHandler PROPERTIES  _BACKTRACE_TRIPLES "T:/Kyle_Shepherd/games/Beyond-All-Reason/data/games/spring/test/CMakeLists.txt;63;add_test;T:/Kyle_Shepherd/games/Beyond-All-Reason/data/games/spring/test/CMakeLists.txt;151;add_spring_test;T:/Kyle_Shepherd/games/Beyond-All-Reason/data/games/spring/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(testRectangleOverlapHandler "T:/Kyle_Shepherd/games/Beyond-All-Reason/data/engine/dev_engine/test/MinSizeRel/test_RectangleOverlapHandler.exe")
  set_tests_properties(testRectangleOverlapHandler PROPERTIES  _BACKTRACE_TRIPLES "T:/Kyle_Shepherd/games/Beyond-All-Reason/data/games/spring/test/CMakeLists.txt;63;add_test;T:/Kyle_Shepherd/games/Beyond-All-Reason/data/games/spring/test/CMakeLists.txt;151;add_spring_test;T:/Kyle_Shepherd/games/Beyond-All-Reason/data/games/spring/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(testRectangleOverlapHandler "T:/Kyle_Shepherd/games/Beyond-All-Reason/data/engine/dev_engine/test/RelWithDebInfo/test_RectangleOverlapHandler.exe")
  set_tests_properties(testRectangleOverlapHandler PROPERTIES  _BACKTRACE_TRIPLES "T:/Kyle_Shepherd/games/Beyond-All-Reason/data/games/spring/test/CMakeLists.txt;63;add_test;T:/Kyle_Shepherd/games/Beyond-All-Reason/data/games/spring/test/CMakeLists.txt;151;add_spring_test;T:/Kyle_Shepherd/games/Beyond-All-Reason/data/games/spring/test/CMakeLists.txt;0;")
else()
  add_test(testRectangleOverlapHandler NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(testFloat3 "T:/Kyle_Shepherd/games/Beyond-All-Reason/data/engine/dev_engine/test/Debug/test_Float3.exe")
  set_tests_properties(testFloat3 PROPERTIES  _BACKTRACE_TRIPLES "T:/Kyle_Shepherd/games/Beyond-All-Reason/data/games/spring/test/CMakeLists.txt;63;add_test;T:/Kyle_Shepherd/games/Beyond-All-Reason/data/games/spring/test/CMakeLists.txt;171;add_spring_test;T:/Kyle_Shepherd/games/Beyond-All-Reason/data/games/spring/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(testFloat3 "T:/Kyle_Shepherd/games/Beyond-All-Reason/data/engine/dev_engine/test/Release/test_Float3.exe")
  set_tests_properties(testFloat3 PROPERTIES  _BACKTRACE_TRIPLES "T:/Kyle_Shepherd/games/Beyond-All-Reason/data/games/spring/test/CMakeLists.txt;63;add_test;T:/Kyle_Shepherd/games/Beyond-All-Reason/data/games/spring/test/CMakeLists.txt;171;add_spring_test;T:/Kyle_Shepherd/games/Beyond-All-Reason/data/games/spring/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(testFloat3 "T:/Kyle_Shepherd/games/Beyond-All-Reason/data/engine/dev_engine/test/MinSizeRel/test_Float3.exe")
  set_tests_properties(testFloat3 PROPERTIES  _BACKTRACE_TRIPLES "T:/Kyle_Shepherd/games/Beyond-All-Reason/data/games/spring/test/CMakeLists.txt;63;add_test;T:/Kyle_Shepherd/games/Beyond-All-Reason/data/games/spring/test/CMakeLists.txt;171;add_spring_test;T:/Kyle_Shepherd/games/Beyond-All-Reason/data/games/spring/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(testFloat3 "T:/Kyle_Shepherd/games/Beyond-All-Reason/data/engine/dev_engine/test/RelWithDebInfo/test_Float3.exe")
  set_tests_properties(testFloat3 PROPERTIES  _BACKTRACE_TRIPLES "T:/Kyle_Shepherd/games/Beyond-All-Reason/data/games/spring/test/CMakeLists.txt;63;add_test;T:/Kyle_Shepherd/games/Beyond-All-Reason/data/games/spring/test/CMakeLists.txt;171;add_spring_test;T:/Kyle_Shepherd/games/Beyond-All-Reason/data/games/spring/test/CMakeLists.txt;0;")
else()
  add_test(testFloat3 NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(testMatrix44f "T:/Kyle_Shepherd/games/Beyond-All-Reason/data/engine/dev_engine/test/Debug/test_Matrix44f.exe")
  set_tests_properties(testMatrix44f PROPERTIES  _BACKTRACE_TRIPLES "T:/Kyle_Shepherd/games/Beyond-All-Reason/data/games/spring/test/CMakeLists.txt;63;add_test;T:/Kyle_Shepherd/games/Beyond-All-Reason/data/games/spring/test/CMakeLists.txt;192;add_spring_test;T:/Kyle_Shepherd/games/Beyond-All-Reason/data/games/spring/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(testMatrix44f "T:/Kyle_Shepherd/games/Beyond-All-Reason/data/engine/dev_engine/test/Release/test_Matrix44f.exe")
  set_tests_properties(testMatrix44f PROPERTIES  _BACKTRACE_TRIPLES "T:/Kyle_Shepherd/games/Beyond-All-Reason/data/games/spring/test/CMakeLists.txt;63;add_test;T:/Kyle_Shepherd/games/Beyond-All-Reason/data/games/spring/test/CMakeLists.txt;192;add_spring_test;T:/Kyle_Shepherd/games/Beyond-All-Reason/data/games/spring/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(testMatrix44f "T:/Kyle_Shepherd/games/Beyond-All-Reason/data/engine/dev_engine/test/MinSizeRel/test_Matrix44f.exe")
  set_tests_properties(testMatrix44f PROPERTIES  _BACKTRACE_TRIPLES "T:/Kyle_Shepherd/games/Beyond-All-Reason/data/games/spring/test/CMakeLists.txt;63;add_test;T:/Kyle_Shepherd/games/Beyond-All-Reason/data/games/spring/test/CMakeLists.txt;192;add_spring_test;T:/Kyle_Shepherd/games/Beyond-All-Reason/data/games/spring/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(testMatrix44f "T:/Kyle_Shepherd/games/Beyond-All-Reason/data/engine/dev_engine/test/RelWithDebInfo/test_Matrix44f.exe")
  set_tests_properties(testMatrix44f PROPERTIES  _BACKTRACE_TRIPLES "T:/Kyle_Shepherd/games/Beyond-All-Reason/data/games/spring/test/CMakeLists.txt;63;add_test;T:/Kyle_Shepherd/games/Beyond-All-Reason/data/games/spring/test/CMakeLists.txt;192;add_spring_test;T:/Kyle_Shepherd/games/Beyond-All-Reason/data/games/spring/test/CMakeLists.txt;0;")
else()
  add_test(testMatrix44f NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(testMatrix44fRotation "T:/Kyle_Shepherd/games/Beyond-All-Reason/data/engine/dev_engine/test/Debug/test_Matrix44fRotation.exe")
  set_tests_properties(testMatrix44fRotation PROPERTIES  _BACKTRACE_TRIPLES "T:/Kyle_Shepherd/games/Beyond-All-Reason/data/games/spring/test/CMakeLists.txt;63;add_test;T:/Kyle_Shepherd/games/Beyond-All-Reason/data/games/spring/test/CMakeLists.txt;209;add_spring_test;T:/Kyle_Shepherd/games/Beyond-All-Reason/data/games/spring/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(testMatrix44fRotation "T:/Kyle_Shepherd/games/Beyond-All-Reason/data/engine/dev_engine/test/Release/test_Matrix44fRotation.exe")
  set_tests_properties(testMatrix44fRotation PROPERTIES  _BACKTRACE_TRIPLES "T:/Kyle_Shepherd/games/Beyond-All-Reason/data/games/spring/test/CMakeLists.txt;63;add_test;T:/Kyle_Shepherd/games/Beyond-All-Reason/data/games/spring/test/CMakeLists.txt;209;add_spring_test;T:/Kyle_Shepherd/games/Beyond-All-Reason/data/games/spring/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(testMatrix44fRotation "T:/Kyle_Shepherd/games/Beyond-All-Reason/data/engine/dev_engine/test/MinSizeRel/test_Matrix44fRotation.exe")
  set_tests_properties(testMatrix44fRotation PROPERTIES  _BACKTRACE_TRIPLES "T:/Kyle_Shepherd/games/Beyond-All-Reason/data/games/spring/test/CMakeLists.txt;63;add_test;T:/Kyle_Shepherd/games/Beyond-All-Reason/data/games/spring/test/CMakeLists.txt;209;add_spring_test;T:/Kyle_Shepherd/games/Beyond-All-Reason/data/games/spring/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(testMatrix44fRotation "T:/Kyle_Shepherd/games/Beyond-All-Reason/data/engine/dev_engine/test/RelWithDebInfo/test_Matrix44fRotation.exe")
  set_tests_properties(testMatrix44fRotation PROPERTIES  _BACKTRACE_TRIPLES "T:/Kyle_Shepherd/games/Beyond-All-Reason/data/games/spring/test/CMakeLists.txt;63;add_test;T:/Kyle_Shepherd/games/Beyond-All-Reason/data/games/spring/test/CMakeLists.txt;209;add_spring_test;T:/Kyle_Shepherd/games/Beyond-All-Reason/data/games/spring/test/CMakeLists.txt;0;")
else()
  add_test(testMatrix44fRotation NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(testSpringTime "T:/Kyle_Shepherd/games/Beyond-All-Reason/data/engine/dev_engine/test/Debug/test_SpringTime.exe")
  set_tests_properties(testSpringTime PROPERTIES  _BACKTRACE_TRIPLES "T:/Kyle_Shepherd/games/Beyond-All-Reason/data/games/spring/test/CMakeLists.txt;63;add_test;T:/Kyle_Shepherd/games/Beyond-All-Reason/data/games/spring/test/CMakeLists.txt;230;add_spring_test;T:/Kyle_Shepherd/games/Beyond-All-Reason/data/games/spring/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(testSpringTime "T:/Kyle_Shepherd/games/Beyond-All-Reason/data/engine/dev_engine/test/Release/test_SpringTime.exe")
  set_tests_properties(testSpringTime PROPERTIES  _BACKTRACE_TRIPLES "T:/Kyle_Shepherd/games/Beyond-All-Reason/data/games/spring/test/CMakeLists.txt;63;add_test;T:/Kyle_Shepherd/games/Beyond-All-Reason/data/games/spring/test/CMakeLists.txt;230;add_spring_test;T:/Kyle_Shepherd/games/Beyond-All-Reason/data/games/spring/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(testSpringTime "T:/Kyle_Shepherd/games/Beyond-All-Reason/data/engine/dev_engine/test/MinSizeRel/test_SpringTime.exe")
  set_tests_properties(testSpringTime PROPERTIES  _BACKTRACE_TRIPLES "T:/Kyle_Shepherd/games/Beyond-All-Reason/data/games/spring/test/CMakeLists.txt;63;add_test;T:/Kyle_Shepherd/games/Beyond-All-Reason/data/games/spring/test/CMakeLists.txt;230;add_spring_test;T:/Kyle_Shepherd/games/Beyond-All-Reason/data/games/spring/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(testSpringTime "T:/Kyle_Shepherd/games/Beyond-All-Reason/data/engine/dev_engine/test/RelWithDebInfo/test_SpringTime.exe")
  set_tests_properties(testSpringTime PROPERTIES  _BACKTRACE_TRIPLES "T:/Kyle_Shepherd/games/Beyond-All-Reason/data/games/spring/test/CMakeLists.txt;63;add_test;T:/Kyle_Shepherd/games/Beyond-All-Reason/data/games/spring/test/CMakeLists.txt;230;add_spring_test;T:/Kyle_Shepherd/games/Beyond-All-Reason/data/games/spring/test/CMakeLists.txt;0;")
else()
  add_test(testSpringTime NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(testBitwiseEnum "T:/Kyle_Shepherd/games/Beyond-All-Reason/data/engine/dev_engine/test/Debug/test_BitwiseEnum.exe")
  set_tests_properties(testBitwiseEnum PROPERTIES  _BACKTRACE_TRIPLES "T:/Kyle_Shepherd/games/Beyond-All-Reason/data/games/spring/test/CMakeLists.txt;63;add_test;T:/Kyle_Shepherd/games/Beyond-All-Reason/data/games/spring/test/CMakeLists.txt;245;add_spring_test;T:/Kyle_Shepherd/games/Beyond-All-Reason/data/games/spring/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(testBitwiseEnum "T:/Kyle_Shepherd/games/Beyond-All-Reason/data/engine/dev_engine/test/Release/test_BitwiseEnum.exe")
  set_tests_properties(testBitwiseEnum PROPERTIES  _BACKTRACE_TRIPLES "T:/Kyle_Shepherd/games/Beyond-All-Reason/data/games/spring/test/CMakeLists.txt;63;add_test;T:/Kyle_Shepherd/games/Beyond-All-Reason/data/games/spring/test/CMakeLists.txt;245;add_spring_test;T:/Kyle_Shepherd/games/Beyond-All-Reason/data/games/spring/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(testBitwiseEnum "T:/Kyle_Shepherd/games/Beyond-All-Reason/data/engine/dev_engine/test/MinSizeRel/test_BitwiseEnum.exe")
  set_tests_properties(testBitwiseEnum PROPERTIES  _BACKTRACE_TRIPLES "T:/Kyle_Shepherd/games/Beyond-All-Reason/data/games/spring/test/CMakeLists.txt;63;add_test;T:/Kyle_Shepherd/games/Beyond-All-Reason/data/games/spring/test/CMakeLists.txt;245;add_spring_test;T:/Kyle_Shepherd/games/Beyond-All-Reason/data/games/spring/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(testBitwiseEnum "T:/Kyle_Shepherd/games/Beyond-All-Reason/data/engine/dev_engine/test/RelWithDebInfo/test_BitwiseEnum.exe")
  set_tests_properties(testBitwiseEnum PROPERTIES  _BACKTRACE_TRIPLES "T:/Kyle_Shepherd/games/Beyond-All-Reason/data/games/spring/test/CMakeLists.txt;63;add_test;T:/Kyle_Shepherd/games/Beyond-All-Reason/data/games/spring/test/CMakeLists.txt;245;add_spring_test;T:/Kyle_Shepherd/games/Beyond-All-Reason/data/games/spring/test/CMakeLists.txt;0;")
else()
  add_test(testBitwiseEnum NOT_AVAILABLE)
endif()
add_test(testBitwiseEnum_fail1 "C:/Program Files/CMake/bin/ctest.exe" "--build-and-test" "T:/Kyle_Shepherd/games/Beyond-All-Reason/data/games/spring/test/tools/CompileFailTest" "T:/Kyle_Shepherd/games/Beyond-All-Reason/data/engine/dev_engine/test/tools/CompileFailTest" "--build-generator" "Visual Studio 16 2019" "--build-makeprogram" "C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/MSBuild/Current/Bin/MSBuild.exe" "--build-project" "CompileFailTest" "--build-options" "-DSOURCE=T:/Kyle_Shepherd/games/Beyond-All-Reason/data/games/spring/test/engine/System/Misc/TestBitwiseEnum.cpp" "-DINCLUDES=:T:/Kyle_Shepherd/games/Beyond-All-Reason/data/games/spring/vclibs64/include:T:/Kyle_Shepherd/games/Beyond-All-Reason/data/engine/dev_engine/src-generated/engine:T:/Kyle_Shepherd/games/Beyond-All-Reason/data/games/spring/rts:T:/Kyle_Shepherd/games/Beyond-All-Reason/data/games/spring/rts/lib/asio/include" "-DDEF_FLAG=\"-DTEST1\"")
set_tests_properties(testBitwiseEnum_fail1 PROPERTIES  WILL_FAIL "ON" _BACKTRACE_TRIPLES "T:/Kyle_Shepherd/games/Beyond-All-Reason/data/games/spring/test/tools/CompileFailTest/CompileFailTest.cmake;23;ADD_TEST;T:/Kyle_Shepherd/games/Beyond-All-Reason/data/games/spring/test/CMakeLists.txt;249;spring_test_compile_fail;T:/Kyle_Shepherd/games/Beyond-All-Reason/data/games/spring/test/CMakeLists.txt;0;")
add_test(testBitwiseEnum_fail2 "C:/Program Files/CMake/bin/ctest.exe" "--build-and-test" "T:/Kyle_Shepherd/games/Beyond-All-Reason/data/games/spring/test/tools/CompileFailTest" "T:/Kyle_Shepherd/games/Beyond-All-Reason/data/engine/dev_engine/test/tools/CompileFailTest" "--build-generator" "Visual Studio 16 2019" "--build-makeprogram" "C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/MSBuild/Current/Bin/MSBuild.exe" "--build-project" "CompileFailTest" "--build-options" "-DSOURCE=T:/Kyle_Shepherd/games/Beyond-All-Reason/data/games/spring/test/engine/System/Misc/TestBitwiseEnum.cpp" "-DINCLUDES=:T:/Kyle_Shepherd/games/Beyond-All-Reason/data/games/spring/vclibs64/include:T:/Kyle_Shepherd/games/Beyond-All-Reason/data/engine/dev_engine/src-generated/engine:T:/Kyle_Shepherd/games/Beyond-All-Reason/data/games/spring/rts:T:/Kyle_Shepherd/games/Beyond-All-Reason/data/games/spring/rts/lib/asio/include" "-DDEF_FLAG=\"-DTEST2\"")
set_tests_properties(testBitwiseEnum_fail2 PROPERTIES  WILL_FAIL "ON" _BACKTRACE_TRIPLES "T:/Kyle_Shepherd/games/Beyond-All-Reason/data/games/spring/test/tools/CompileFailTest/CompileFailTest.cmake;23;ADD_TEST;T:/Kyle_Shepherd/games/Beyond-All-Reason/data/games/spring/test/CMakeLists.txt;250;spring_test_compile_fail;T:/Kyle_Shepherd/games/Beyond-All-Reason/data/games/spring/test/CMakeLists.txt;0;")
add_test(testBitwiseEnum_fail3 "C:/Program Files/CMake/bin/ctest.exe" "--build-and-test" "T:/Kyle_Shepherd/games/Beyond-All-Reason/data/games/spring/test/tools/CompileFailTest" "T:/Kyle_Shepherd/games/Beyond-All-Reason/data/engine/dev_engine/test/tools/CompileFailTest" "--build-generator" "Visual Studio 16 2019" "--build-makeprogram" "C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/MSBuild/Current/Bin/MSBuild.exe" "--build-project" "CompileFailTest" "--build-options" "-DSOURCE=T:/Kyle_Shepherd/games/Beyond-All-Reason/data/games/spring/test/engine/System/Misc/TestBitwiseEnum.cpp" "-DINCLUDES=:T:/Kyle_Shepherd/games/Beyond-All-Reason/data/games/spring/vclibs64/include:T:/Kyle_Shepherd/games/Beyond-All-Reason/data/engine/dev_engine/src-generated/engine:T:/Kyle_Shepherd/games/Beyond-All-Reason/data/games/spring/rts:T:/Kyle_Shepherd/games/Beyond-All-Reason/data/games/spring/rts/lib/asio/include" "-DDEF_FLAG=\"-DTEST3\"")
set_tests_properties(testBitwiseEnum_fail3 PROPERTIES  WILL_FAIL "ON" _BACKTRACE_TRIPLES "T:/Kyle_Shepherd/games/Beyond-All-Reason/data/games/spring/test/tools/CompileFailTest/CompileFailTest.cmake;23;ADD_TEST;T:/Kyle_Shepherd/games/Beyond-All-Reason/data/games/spring/test/CMakeLists.txt;251;spring_test_compile_fail;T:/Kyle_Shepherd/games/Beyond-All-Reason/data/games/spring/test/CMakeLists.txt;0;")
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(testFileSystem "T:/Kyle_Shepherd/games/Beyond-All-Reason/data/engine/dev_engine/test/Debug/test_FileSystem.exe")
  set_tests_properties(testFileSystem PROPERTIES  _BACKTRACE_TRIPLES "T:/Kyle_Shepherd/games/Beyond-All-Reason/data/games/spring/test/CMakeLists.txt;63;add_test;T:/Kyle_Shepherd/games/Beyond-All-Reason/data/games/spring/test/CMakeLists.txt;271;add_spring_test;T:/Kyle_Shepherd/games/Beyond-All-Reason/data/games/spring/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(testFileSystem "T:/Kyle_Shepherd/games/Beyond-All-Reason/data/engine/dev_engine/test/Release/test_FileSystem.exe")
  set_tests_properties(testFileSystem PROPERTIES  _BACKTRACE_TRIPLES "T:/Kyle_Shepherd/games/Beyond-All-Reason/data/games/spring/test/CMakeLists.txt;63;add_test;T:/Kyle_Shepherd/games/Beyond-All-Reason/data/games/spring/test/CMakeLists.txt;271;add_spring_test;T:/Kyle_Shepherd/games/Beyond-All-Reason/data/games/spring/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(testFileSystem "T:/Kyle_Shepherd/games/Beyond-All-Reason/data/engine/dev_engine/test/MinSizeRel/test_FileSystem.exe")
  set_tests_properties(testFileSystem PROPERTIES  _BACKTRACE_TRIPLES "T:/Kyle_Shepherd/games/Beyond-All-Reason/data/games/spring/test/CMakeLists.txt;63;add_test;T:/Kyle_Shepherd/games/Beyond-All-Reason/data/games/spring/test/CMakeLists.txt;271;add_spring_test;T:/Kyle_Shepherd/games/Beyond-All-Reason/data/games/spring/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(testFileSystem "T:/Kyle_Shepherd/games/Beyond-All-Reason/data/engine/dev_engine/test/RelWithDebInfo/test_FileSystem.exe")
  set_tests_properties(testFileSystem PROPERTIES  _BACKTRACE_TRIPLES "T:/Kyle_Shepherd/games/Beyond-All-Reason/data/games/spring/test/CMakeLists.txt;63;add_test;T:/Kyle_Shepherd/games/Beyond-All-Reason/data/games/spring/test/CMakeLists.txt;271;add_spring_test;T:/Kyle_Shepherd/games/Beyond-All-Reason/data/games/spring/test/CMakeLists.txt;0;")
else()
  add_test(testFileSystem NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(testLuaSocketRestrictions "T:/Kyle_Shepherd/games/Beyond-All-Reason/data/engine/dev_engine/test/Debug/test_LuaSocketRestrictions.exe")
  set_tests_properties(testLuaSocketRestrictions PROPERTIES  _BACKTRACE_TRIPLES "T:/Kyle_Shepherd/games/Beyond-All-Reason/data/games/spring/test/CMakeLists.txt;63;add_test;T:/Kyle_Shepherd/games/Beyond-All-Reason/data/games/spring/test/CMakeLists.txt;286;add_spring_test;T:/Kyle_Shepherd/games/Beyond-All-Reason/data/games/spring/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(testLuaSocketRestrictions "T:/Kyle_Shepherd/games/Beyond-All-Reason/data/engine/dev_engine/test/Release/test_LuaSocketRestrictions.exe")
  set_tests_properties(testLuaSocketRestrictions PROPERTIES  _BACKTRACE_TRIPLES "T:/Kyle_Shepherd/games/Beyond-All-Reason/data/games/spring/test/CMakeLists.txt;63;add_test;T:/Kyle_Shepherd/games/Beyond-All-Reason/data/games/spring/test/CMakeLists.txt;286;add_spring_test;T:/Kyle_Shepherd/games/Beyond-All-Reason/data/games/spring/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(testLuaSocketRestrictions "T:/Kyle_Shepherd/games/Beyond-All-Reason/data/engine/dev_engine/test/MinSizeRel/test_LuaSocketRestrictions.exe")
  set_tests_properties(testLuaSocketRestrictions PROPERTIES  _BACKTRACE_TRIPLES "T:/Kyle_Shepherd/games/Beyond-All-Reason/data/games/spring/test/CMakeLists.txt;63;add_test;T:/Kyle_Shepherd/games/Beyond-All-Reason/data/games/spring/test/CMakeLists.txt;286;add_spring_test;T:/Kyle_Shepherd/games/Beyond-All-Reason/data/games/spring/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(testLuaSocketRestrictions "T:/Kyle_Shepherd/games/Beyond-All-Reason/data/engine/dev_engine/test/RelWithDebInfo/test_LuaSocketRestrictions.exe")
  set_tests_properties(testLuaSocketRestrictions PROPERTIES  _BACKTRACE_TRIPLES "T:/Kyle_Shepherd/games/Beyond-All-Reason/data/games/spring/test/CMakeLists.txt;63;add_test;T:/Kyle_Shepherd/games/Beyond-All-Reason/data/games/spring/test/CMakeLists.txt;286;add_spring_test;T:/Kyle_Shepherd/games/Beyond-All-Reason/data/games/spring/test/CMakeLists.txt;0;")
else()
  add_test(testLuaSocketRestrictions NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(testCreg "T:/Kyle_Shepherd/games/Beyond-All-Reason/data/engine/dev_engine/spring-headless.exe" "--test-creg")
  set_tests_properties(testCreg PROPERTIES  _BACKTRACE_TRIPLES "T:/Kyle_Shepherd/games/Beyond-All-Reason/data/games/spring/test/CMakeLists.txt;291;add_test;T:/Kyle_Shepherd/games/Beyond-All-Reason/data/games/spring/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(testCreg "T:/Kyle_Shepherd/games/Beyond-All-Reason/data/engine/dev_engine/spring-headless.exe" "--test-creg")
  set_tests_properties(testCreg PROPERTIES  _BACKTRACE_TRIPLES "T:/Kyle_Shepherd/games/Beyond-All-Reason/data/games/spring/test/CMakeLists.txt;291;add_test;T:/Kyle_Shepherd/games/Beyond-All-Reason/data/games/spring/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(testCreg "T:/Kyle_Shepherd/games/Beyond-All-Reason/data/engine/dev_engine/spring-headless.exe" "--test-creg")
  set_tests_properties(testCreg PROPERTIES  _BACKTRACE_TRIPLES "T:/Kyle_Shepherd/games/Beyond-All-Reason/data/games/spring/test/CMakeLists.txt;291;add_test;T:/Kyle_Shepherd/games/Beyond-All-Reason/data/games/spring/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(testCreg "T:/Kyle_Shepherd/games/Beyond-All-Reason/data/engine/dev_engine/spring-headless.exe" "--test-creg")
  set_tests_properties(testCreg PROPERTIES  _BACKTRACE_TRIPLES "T:/Kyle_Shepherd/games/Beyond-All-Reason/data/games/spring/test/CMakeLists.txt;291;add_test;T:/Kyle_Shepherd/games/Beyond-All-Reason/data/games/spring/test/CMakeLists.txt;0;")
else()
  add_test(testCreg NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(testLoadSave "T:/Kyle_Shepherd/games/Beyond-All-Reason/data/engine/dev_engine/test/Debug/test_LoadSave.exe")
  set_tests_properties(testLoadSave PROPERTIES  _BACKTRACE_TRIPLES "T:/Kyle_Shepherd/games/Beyond-All-Reason/data/games/spring/test/CMakeLists.txt;63;add_test;T:/Kyle_Shepherd/games/Beyond-All-Reason/data/games/spring/test/CMakeLists.txt;307;add_spring_test;T:/Kyle_Shepherd/games/Beyond-All-Reason/data/games/spring/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(testLoadSave "T:/Kyle_Shepherd/games/Beyond-All-Reason/data/engine/dev_engine/test/Release/test_LoadSave.exe")
  set_tests_properties(testLoadSave PROPERTIES  _BACKTRACE_TRIPLES "T:/Kyle_Shepherd/games/Beyond-All-Reason/data/games/spring/test/CMakeLists.txt;63;add_test;T:/Kyle_Shepherd/games/Beyond-All-Reason/data/games/spring/test/CMakeLists.txt;307;add_spring_test;T:/Kyle_Shepherd/games/Beyond-All-Reason/data/games/spring/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(testLoadSave "T:/Kyle_Shepherd/games/Beyond-All-Reason/data/engine/dev_engine/test/MinSizeRel/test_LoadSave.exe")
  set_tests_properties(testLoadSave PROPERTIES  _BACKTRACE_TRIPLES "T:/Kyle_Shepherd/games/Beyond-All-Reason/data/games/spring/test/CMakeLists.txt;63;add_test;T:/Kyle_Shepherd/games/Beyond-All-Reason/data/games/spring/test/CMakeLists.txt;307;add_spring_test;T:/Kyle_Shepherd/games/Beyond-All-Reason/data/games/spring/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(testLoadSave "T:/Kyle_Shepherd/games/Beyond-All-Reason/data/engine/dev_engine/test/RelWithDebInfo/test_LoadSave.exe")
  set_tests_properties(testLoadSave PROPERTIES  _BACKTRACE_TRIPLES "T:/Kyle_Shepherd/games/Beyond-All-Reason/data/games/spring/test/CMakeLists.txt;63;add_test;T:/Kyle_Shepherd/games/Beyond-All-Reason/data/games/spring/test/CMakeLists.txt;307;add_spring_test;T:/Kyle_Shepherd/games/Beyond-All-Reason/data/games/spring/test/CMakeLists.txt;0;")
else()
  add_test(testLoadSave NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(testUnitSync "T:/Kyle_Shepherd/games/Beyond-All-Reason/data/engine/dev_engine/test/Debug/test_UnitSync.exe")
  set_tests_properties(testUnitSync PROPERTIES  _BACKTRACE_TRIPLES "T:/Kyle_Shepherd/games/Beyond-All-Reason/data/games/spring/test/CMakeLists.txt;63;add_test;T:/Kyle_Shepherd/games/Beyond-All-Reason/data/games/spring/test/CMakeLists.txt;331;add_spring_test;T:/Kyle_Shepherd/games/Beyond-All-Reason/data/games/spring/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(testUnitSync "T:/Kyle_Shepherd/games/Beyond-All-Reason/data/engine/dev_engine/test/Release/test_UnitSync.exe")
  set_tests_properties(testUnitSync PROPERTIES  _BACKTRACE_TRIPLES "T:/Kyle_Shepherd/games/Beyond-All-Reason/data/games/spring/test/CMakeLists.txt;63;add_test;T:/Kyle_Shepherd/games/Beyond-All-Reason/data/games/spring/test/CMakeLists.txt;331;add_spring_test;T:/Kyle_Shepherd/games/Beyond-All-Reason/data/games/spring/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(testUnitSync "T:/Kyle_Shepherd/games/Beyond-All-Reason/data/engine/dev_engine/test/MinSizeRel/test_UnitSync.exe")
  set_tests_properties(testUnitSync PROPERTIES  _BACKTRACE_TRIPLES "T:/Kyle_Shepherd/games/Beyond-All-Reason/data/games/spring/test/CMakeLists.txt;63;add_test;T:/Kyle_Shepherd/games/Beyond-All-Reason/data/games/spring/test/CMakeLists.txt;331;add_spring_test;T:/Kyle_Shepherd/games/Beyond-All-Reason/data/games/spring/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(testUnitSync "T:/Kyle_Shepherd/games/Beyond-All-Reason/data/engine/dev_engine/test/RelWithDebInfo/test_UnitSync.exe")
  set_tests_properties(testUnitSync PROPERTIES  _BACKTRACE_TRIPLES "T:/Kyle_Shepherd/games/Beyond-All-Reason/data/games/spring/test/CMakeLists.txt;63;add_test;T:/Kyle_Shepherd/games/Beyond-All-Reason/data/games/spring/test/CMakeLists.txt;331;add_spring_test;T:/Kyle_Shepherd/games/Beyond-All-Reason/data/games/spring/test/CMakeLists.txt;0;")
else()
  add_test(testUnitSync NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(testThreadPool "T:/Kyle_Shepherd/games/Beyond-All-Reason/data/engine/dev_engine/test/Debug/test_ThreadPool.exe")
  set_tests_properties(testThreadPool PROPERTIES  _BACKTRACE_TRIPLES "T:/Kyle_Shepherd/games/Beyond-All-Reason/data/games/spring/test/CMakeLists.txt;63;add_test;T:/Kyle_Shepherd/games/Beyond-All-Reason/data/games/spring/test/CMakeLists.txt;353;add_spring_test;T:/Kyle_Shepherd/games/Beyond-All-Reason/data/games/spring/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(testThreadPool "T:/Kyle_Shepherd/games/Beyond-All-Reason/data/engine/dev_engine/test/Release/test_ThreadPool.exe")
  set_tests_properties(testThreadPool PROPERTIES  _BACKTRACE_TRIPLES "T:/Kyle_Shepherd/games/Beyond-All-Reason/data/games/spring/test/CMakeLists.txt;63;add_test;T:/Kyle_Shepherd/games/Beyond-All-Reason/data/games/spring/test/CMakeLists.txt;353;add_spring_test;T:/Kyle_Shepherd/games/Beyond-All-Reason/data/games/spring/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(testThreadPool "T:/Kyle_Shepherd/games/Beyond-All-Reason/data/engine/dev_engine/test/MinSizeRel/test_ThreadPool.exe")
  set_tests_properties(testThreadPool PROPERTIES  _BACKTRACE_TRIPLES "T:/Kyle_Shepherd/games/Beyond-All-Reason/data/games/spring/test/CMakeLists.txt;63;add_test;T:/Kyle_Shepherd/games/Beyond-All-Reason/data/games/spring/test/CMakeLists.txt;353;add_spring_test;T:/Kyle_Shepherd/games/Beyond-All-Reason/data/games/spring/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(testThreadPool "T:/Kyle_Shepherd/games/Beyond-All-Reason/data/engine/dev_engine/test/RelWithDebInfo/test_ThreadPool.exe")
  set_tests_properties(testThreadPool PROPERTIES  _BACKTRACE_TRIPLES "T:/Kyle_Shepherd/games/Beyond-All-Reason/data/games/spring/test/CMakeLists.txt;63;add_test;T:/Kyle_Shepherd/games/Beyond-All-Reason/data/games/spring/test/CMakeLists.txt;353;add_spring_test;T:/Kyle_Shepherd/games/Beyond-All-Reason/data/games/spring/test/CMakeLists.txt;0;")
else()
  add_test(testThreadPool NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(testMutex "T:/Kyle_Shepherd/games/Beyond-All-Reason/data/engine/dev_engine/test/Debug/test_Mutex.exe")
  set_tests_properties(testMutex PROPERTIES  _BACKTRACE_TRIPLES "T:/Kyle_Shepherd/games/Beyond-All-Reason/data/games/spring/test/CMakeLists.txt;63;add_test;T:/Kyle_Shepherd/games/Beyond-All-Reason/data/games/spring/test/CMakeLists.txt;375;add_spring_test;T:/Kyle_Shepherd/games/Beyond-All-Reason/data/games/spring/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(testMutex "T:/Kyle_Shepherd/games/Beyond-All-Reason/data/engine/dev_engine/test/Release/test_Mutex.exe")
  set_tests_properties(testMutex PROPERTIES  _BACKTRACE_TRIPLES "T:/Kyle_Shepherd/games/Beyond-All-Reason/data/games/spring/test/CMakeLists.txt;63;add_test;T:/Kyle_Shepherd/games/Beyond-All-Reason/data/games/spring/test/CMakeLists.txt;375;add_spring_test;T:/Kyle_Shepherd/games/Beyond-All-Reason/data/games/spring/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(testMutex "T:/Kyle_Shepherd/games/Beyond-All-Reason/data/engine/dev_engine/test/MinSizeRel/test_Mutex.exe")
  set_tests_properties(testMutex PROPERTIES  _BACKTRACE_TRIPLES "T:/Kyle_Shepherd/games/Beyond-All-Reason/data/games/spring/test/CMakeLists.txt;63;add_test;T:/Kyle_Shepherd/games/Beyond-All-Reason/data/games/spring/test/CMakeLists.txt;375;add_spring_test;T:/Kyle_Shepherd/games/Beyond-All-Reason/data/games/spring/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(testMutex "T:/Kyle_Shepherd/games/Beyond-All-Reason/data/engine/dev_engine/test/RelWithDebInfo/test_Mutex.exe")
  set_tests_properties(testMutex PROPERTIES  _BACKTRACE_TRIPLES "T:/Kyle_Shepherd/games/Beyond-All-Reason/data/games/spring/test/CMakeLists.txt;63;add_test;T:/Kyle_Shepherd/games/Beyond-All-Reason/data/games/spring/test/CMakeLists.txt;375;add_spring_test;T:/Kyle_Shepherd/games/Beyond-All-Reason/data/games/spring/test/CMakeLists.txt;0;")
else()
  add_test(testMutex NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(testEllipsoid "T:/Kyle_Shepherd/games/Beyond-All-Reason/data/engine/dev_engine/test/Debug/test_Ellipsoid.exe")
  set_tests_properties(testEllipsoid PROPERTIES  _BACKTRACE_TRIPLES "T:/Kyle_Shepherd/games/Beyond-All-Reason/data/games/spring/test/CMakeLists.txt;63;add_test;T:/Kyle_Shepherd/games/Beyond-All-Reason/data/games/spring/test/CMakeLists.txt;388;add_spring_test;T:/Kyle_Shepherd/games/Beyond-All-Reason/data/games/spring/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(testEllipsoid "T:/Kyle_Shepherd/games/Beyond-All-Reason/data/engine/dev_engine/test/Release/test_Ellipsoid.exe")
  set_tests_properties(testEllipsoid PROPERTIES  _BACKTRACE_TRIPLES "T:/Kyle_Shepherd/games/Beyond-All-Reason/data/games/spring/test/CMakeLists.txt;63;add_test;T:/Kyle_Shepherd/games/Beyond-All-Reason/data/games/spring/test/CMakeLists.txt;388;add_spring_test;T:/Kyle_Shepherd/games/Beyond-All-Reason/data/games/spring/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(testEllipsoid "T:/Kyle_Shepherd/games/Beyond-All-Reason/data/engine/dev_engine/test/MinSizeRel/test_Ellipsoid.exe")
  set_tests_properties(testEllipsoid PROPERTIES  _BACKTRACE_TRIPLES "T:/Kyle_Shepherd/games/Beyond-All-Reason/data/games/spring/test/CMakeLists.txt;63;add_test;T:/Kyle_Shepherd/games/Beyond-All-Reason/data/games/spring/test/CMakeLists.txt;388;add_spring_test;T:/Kyle_Shepherd/games/Beyond-All-Reason/data/games/spring/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(testEllipsoid "T:/Kyle_Shepherd/games/Beyond-All-Reason/data/engine/dev_engine/test/RelWithDebInfo/test_Ellipsoid.exe")
  set_tests_properties(testEllipsoid PROPERTIES  _BACKTRACE_TRIPLES "T:/Kyle_Shepherd/games/Beyond-All-Reason/data/games/spring/test/CMakeLists.txt;63;add_test;T:/Kyle_Shepherd/games/Beyond-All-Reason/data/games/spring/test/CMakeLists.txt;388;add_spring_test;T:/Kyle_Shepherd/games/Beyond-All-Reason/data/games/spring/test/CMakeLists.txt;0;")
else()
  add_test(testEllipsoid NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(testQuadField "T:/Kyle_Shepherd/games/Beyond-All-Reason/data/engine/dev_engine/test/Debug/test_QuadField.exe")
  set_tests_properties(testQuadField PROPERTIES  _BACKTRACE_TRIPLES "T:/Kyle_Shepherd/games/Beyond-All-Reason/data/games/spring/test/CMakeLists.txt;63;add_test;T:/Kyle_Shepherd/games/Beyond-All-Reason/data/games/spring/test/CMakeLists.txt;402;add_spring_test;T:/Kyle_Shepherd/games/Beyond-All-Reason/data/games/spring/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(testQuadField "T:/Kyle_Shepherd/games/Beyond-All-Reason/data/engine/dev_engine/test/Release/test_QuadField.exe")
  set_tests_properties(testQuadField PROPERTIES  _BACKTRACE_TRIPLES "T:/Kyle_Shepherd/games/Beyond-All-Reason/data/games/spring/test/CMakeLists.txt;63;add_test;T:/Kyle_Shepherd/games/Beyond-All-Reason/data/games/spring/test/CMakeLists.txt;402;add_spring_test;T:/Kyle_Shepherd/games/Beyond-All-Reason/data/games/spring/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(testQuadField "T:/Kyle_Shepherd/games/Beyond-All-Reason/data/engine/dev_engine/test/MinSizeRel/test_QuadField.exe")
  set_tests_properties(testQuadField PROPERTIES  _BACKTRACE_TRIPLES "T:/Kyle_Shepherd/games/Beyond-All-Reason/data/games/spring/test/CMakeLists.txt;63;add_test;T:/Kyle_Shepherd/games/Beyond-All-Reason/data/games/spring/test/CMakeLists.txt;402;add_spring_test;T:/Kyle_Shepherd/games/Beyond-All-Reason/data/games/spring/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(testQuadField "T:/Kyle_Shepherd/games/Beyond-All-Reason/data/engine/dev_engine/test/RelWithDebInfo/test_QuadField.exe")
  set_tests_properties(testQuadField PROPERTIES  _BACKTRACE_TRIPLES "T:/Kyle_Shepherd/games/Beyond-All-Reason/data/games/spring/test/CMakeLists.txt;63;add_test;T:/Kyle_Shepherd/games/Beyond-All-Reason/data/games/spring/test/CMakeLists.txt;402;add_spring_test;T:/Kyle_Shepherd/games/Beyond-All-Reason/data/games/spring/test/CMakeLists.txt;0;")
else()
  add_test(testQuadField NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(testPrintf "T:/Kyle_Shepherd/games/Beyond-All-Reason/data/engine/dev_engine/test/Debug/test_Printf.exe")
  set_tests_properties(testPrintf PROPERTIES  _BACKTRACE_TRIPLES "T:/Kyle_Shepherd/games/Beyond-All-Reason/data/games/spring/test/CMakeLists.txt;63;add_test;T:/Kyle_Shepherd/games/Beyond-All-Reason/data/games/spring/test/CMakeLists.txt;423;add_spring_test;T:/Kyle_Shepherd/games/Beyond-All-Reason/data/games/spring/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(testPrintf "T:/Kyle_Shepherd/games/Beyond-All-Reason/data/engine/dev_engine/test/Release/test_Printf.exe")
  set_tests_properties(testPrintf PROPERTIES  _BACKTRACE_TRIPLES "T:/Kyle_Shepherd/games/Beyond-All-Reason/data/games/spring/test/CMakeLists.txt;63;add_test;T:/Kyle_Shepherd/games/Beyond-All-Reason/data/games/spring/test/CMakeLists.txt;423;add_spring_test;T:/Kyle_Shepherd/games/Beyond-All-Reason/data/games/spring/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(testPrintf "T:/Kyle_Shepherd/games/Beyond-All-Reason/data/engine/dev_engine/test/MinSizeRel/test_Printf.exe")
  set_tests_properties(testPrintf PROPERTIES  _BACKTRACE_TRIPLES "T:/Kyle_Shepherd/games/Beyond-All-Reason/data/games/spring/test/CMakeLists.txt;63;add_test;T:/Kyle_Shepherd/games/Beyond-All-Reason/data/games/spring/test/CMakeLists.txt;423;add_spring_test;T:/Kyle_Shepherd/games/Beyond-All-Reason/data/games/spring/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(testPrintf "T:/Kyle_Shepherd/games/Beyond-All-Reason/data/engine/dev_engine/test/RelWithDebInfo/test_Printf.exe")
  set_tests_properties(testPrintf PROPERTIES  _BACKTRACE_TRIPLES "T:/Kyle_Shepherd/games/Beyond-All-Reason/data/games/spring/test/CMakeLists.txt;63;add_test;T:/Kyle_Shepherd/games/Beyond-All-Reason/data/games/spring/test/CMakeLists.txt;423;add_spring_test;T:/Kyle_Shepherd/games/Beyond-All-Reason/data/games/spring/test/CMakeLists.txt;0;")
else()
  add_test(testPrintf NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(testSQRT "T:/Kyle_Shepherd/games/Beyond-All-Reason/data/engine/dev_engine/test/Debug/test_SQRT.exe")
  set_tests_properties(testSQRT PROPERTIES  _BACKTRACE_TRIPLES "T:/Kyle_Shepherd/games/Beyond-All-Reason/data/games/spring/test/CMakeLists.txt;63;add_test;T:/Kyle_Shepherd/games/Beyond-All-Reason/data/games/spring/test/CMakeLists.txt;443;add_spring_test;T:/Kyle_Shepherd/games/Beyond-All-Reason/data/games/spring/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(testSQRT "T:/Kyle_Shepherd/games/Beyond-All-Reason/data/engine/dev_engine/test/Release/test_SQRT.exe")
  set_tests_properties(testSQRT PROPERTIES  _BACKTRACE_TRIPLES "T:/Kyle_Shepherd/games/Beyond-All-Reason/data/games/spring/test/CMakeLists.txt;63;add_test;T:/Kyle_Shepherd/games/Beyond-All-Reason/data/games/spring/test/CMakeLists.txt;443;add_spring_test;T:/Kyle_Shepherd/games/Beyond-All-Reason/data/games/spring/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(testSQRT "T:/Kyle_Shepherd/games/Beyond-All-Reason/data/engine/dev_engine/test/MinSizeRel/test_SQRT.exe")
  set_tests_properties(testSQRT PROPERTIES  _BACKTRACE_TRIPLES "T:/Kyle_Shepherd/games/Beyond-All-Reason/data/games/spring/test/CMakeLists.txt;63;add_test;T:/Kyle_Shepherd/games/Beyond-All-Reason/data/games/spring/test/CMakeLists.txt;443;add_spring_test;T:/Kyle_Shepherd/games/Beyond-All-Reason/data/games/spring/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(testSQRT "T:/Kyle_Shepherd/games/Beyond-All-Reason/data/engine/dev_engine/test/RelWithDebInfo/test_SQRT.exe")
  set_tests_properties(testSQRT PROPERTIES  _BACKTRACE_TRIPLES "T:/Kyle_Shepherd/games/Beyond-All-Reason/data/games/spring/test/CMakeLists.txt;63;add_test;T:/Kyle_Shepherd/games/Beyond-All-Reason/data/games/spring/test/CMakeLists.txt;443;add_spring_test;T:/Kyle_Shepherd/games/Beyond-All-Reason/data/games/spring/test/CMakeLists.txt;0;")
else()
  add_test(testSQRT NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(testEventClient "T:/Kyle_Shepherd/games/Beyond-All-Reason/data/engine/dev_engine/test/Debug/test_EventClient.exe")
  set_tests_properties(testEventClient PROPERTIES  _BACKTRACE_TRIPLES "T:/Kyle_Shepherd/games/Beyond-All-Reason/data/games/spring/test/CMakeLists.txt;63;add_test;T:/Kyle_Shepherd/games/Beyond-All-Reason/data/games/spring/test/CMakeLists.txt;455;add_spring_test;T:/Kyle_Shepherd/games/Beyond-All-Reason/data/games/spring/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(testEventClient "T:/Kyle_Shepherd/games/Beyond-All-Reason/data/engine/dev_engine/test/Release/test_EventClient.exe")
  set_tests_properties(testEventClient PROPERTIES  _BACKTRACE_TRIPLES "T:/Kyle_Shepherd/games/Beyond-All-Reason/data/games/spring/test/CMakeLists.txt;63;add_test;T:/Kyle_Shepherd/games/Beyond-All-Reason/data/games/spring/test/CMakeLists.txt;455;add_spring_test;T:/Kyle_Shepherd/games/Beyond-All-Reason/data/games/spring/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(testEventClient "T:/Kyle_Shepherd/games/Beyond-All-Reason/data/engine/dev_engine/test/MinSizeRel/test_EventClient.exe")
  set_tests_properties(testEventClient PROPERTIES  _BACKTRACE_TRIPLES "T:/Kyle_Shepherd/games/Beyond-All-Reason/data/games/spring/test/CMakeLists.txt;63;add_test;T:/Kyle_Shepherd/games/Beyond-All-Reason/data/games/spring/test/CMakeLists.txt;455;add_spring_test;T:/Kyle_Shepherd/games/Beyond-All-Reason/data/games/spring/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(testEventClient "T:/Kyle_Shepherd/games/Beyond-All-Reason/data/engine/dev_engine/test/RelWithDebInfo/test_EventClient.exe")
  set_tests_properties(testEventClient PROPERTIES  _BACKTRACE_TRIPLES "T:/Kyle_Shepherd/games/Beyond-All-Reason/data/games/spring/test/CMakeLists.txt;63;add_test;T:/Kyle_Shepherd/games/Beyond-All-Reason/data/games/spring/test/CMakeLists.txt;455;add_spring_test;T:/Kyle_Shepherd/games/Beyond-All-Reason/data/games/spring/test/CMakeLists.txt;0;")
else()
  add_test(testEventClient NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(testSerializeLuaState "T:/Kyle_Shepherd/games/Beyond-All-Reason/data/engine/dev_engine/test/Debug/test_SerializeLuaState.exe")
  set_tests_properties(testSerializeLuaState PROPERTIES  _BACKTRACE_TRIPLES "T:/Kyle_Shepherd/games/Beyond-All-Reason/data/games/spring/test/CMakeLists.txt;63;add_test;T:/Kyle_Shepherd/games/Beyond-All-Reason/data/games/spring/test/CMakeLists.txt;476;add_spring_test;T:/Kyle_Shepherd/games/Beyond-All-Reason/data/games/spring/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(testSerializeLuaState "T:/Kyle_Shepherd/games/Beyond-All-Reason/data/engine/dev_engine/test/Release/test_SerializeLuaState.exe")
  set_tests_properties(testSerializeLuaState PROPERTIES  _BACKTRACE_TRIPLES "T:/Kyle_Shepherd/games/Beyond-All-Reason/data/games/spring/test/CMakeLists.txt;63;add_test;T:/Kyle_Shepherd/games/Beyond-All-Reason/data/games/spring/test/CMakeLists.txt;476;add_spring_test;T:/Kyle_Shepherd/games/Beyond-All-Reason/data/games/spring/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(testSerializeLuaState "T:/Kyle_Shepherd/games/Beyond-All-Reason/data/engine/dev_engine/test/MinSizeRel/test_SerializeLuaState.exe")
  set_tests_properties(testSerializeLuaState PROPERTIES  _BACKTRACE_TRIPLES "T:/Kyle_Shepherd/games/Beyond-All-Reason/data/games/spring/test/CMakeLists.txt;63;add_test;T:/Kyle_Shepherd/games/Beyond-All-Reason/data/games/spring/test/CMakeLists.txt;476;add_spring_test;T:/Kyle_Shepherd/games/Beyond-All-Reason/data/games/spring/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(testSerializeLuaState "T:/Kyle_Shepherd/games/Beyond-All-Reason/data/engine/dev_engine/test/RelWithDebInfo/test_SerializeLuaState.exe")
  set_tests_properties(testSerializeLuaState PROPERTIES  _BACKTRACE_TRIPLES "T:/Kyle_Shepherd/games/Beyond-All-Reason/data/games/spring/test/CMakeLists.txt;63;add_test;T:/Kyle_Shepherd/games/Beyond-All-Reason/data/games/spring/test/CMakeLists.txt;476;add_spring_test;T:/Kyle_Shepherd/games/Beyond-All-Reason/data/games/spring/test/CMakeLists.txt;0;")
else()
  add_test(testSerializeLuaState NOT_AVAILABLE)
endif()
subdirs("headercheck")
